name: Dify Release Notifier

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check latest release from langgenius/dify
      id: latest-release
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: 'langgenius',
            repo: 'dify'
          });
          return release.data.tag_name;

    - name: Send notification email if new release detected
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: New Release Detected in langgenius/dify
        body: The repository langgenius/dify has a new release: ${{ steps.latest-release.outputs.result }}
        to: gaofan@deepexi.com
        from: sunnygaofan@gmail.com
