name: Dify Release Notifier

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:
    inputs:
      isrun:
        description: '是否运行'
        type: boolean
        required: false

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check latest release from langgenius/dify
      id: latest-release
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: 'langgenius',
            repo: 'dify'
          });
          const releaseDate = new Date(release.data.published_at);
          const chinaReleaseDate = releaseDate.toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' });
          const releaseData = {
            tag_name: release.data.tag_name,
            html_url: release.data.html_url,
            body: release.data.body,
            published_at: chinaReleaseDate
          };
          return releaseData;

    - name: Get result
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        script: |
          print(${{ steps.latest-release.outputs }})
        
    - name: Send notification email if new release detected
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: dify新版本发布：${{ steps.latest-release.outputs.tag_name }}
        body: |
          langgenius/dify 发布了新版本

          **版本:** ${{ steps.latest-release.outputs.tag_name }}
          **发布时间:** ${{ steps.latest-release.outputs.published_at }}
          **更新内容:** ${{ steps.latest-release.outputs.body }}
          **链接:** ${{ steps.latest-release.outputs.html_url }}
        to: gaofan@deepexi.com
        from: ${{ secrets.EMAIL_USERNAME }}
