name: Dify Release Notifier

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:
    inputs:
      isrun:
        description: '是否运行'
        type: boolean
        required: false

permissions:
  contents: read
  actions: write

jobs:
  check-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get last release version
      shell: bash
      id: get-last-version
      run: |
        if [ -f last_release_version.txt ]; then
          cat last_release_version.txt
        else
          echo "none"
        fi
        
    - name: Install dependencies
      run: npm install markdown-it
      
    - name: Check latest release from langgenius/dify
      id: latest-release
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const markdown = require('markdown-it')();
          const fs = require('fs');
          const release = await github.rest.repos.getLatestRelease({
            owner: 'langgenius',
            repo: 'dify'
          });
          
          const lastReleaseVersion = process.env.LAST_RELEASE_VERSION;
          if (release.data.tag_name !== lastReleaseVersion + 1) {
            core.setOutput('new_release', 'true');
            fs.writeFileSync('last_release_version.txt', release.data.tag_name);
          } else {
            core.setOutput('new_release', 'false');
          }

          const releaseDate = new Date(release.data.published_at);
          const chinaReleaseDate = releaseDate.toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' });
          const htmlBody = markdown.render(release.data.body);
          core.setOutput("tag_name", release.data.tag_name);
          core.setOutput("html_url", release.data.html_url);
          core.setOutput("content", htmlBody);
          core.setOutput("published_at", chinaReleaseDate);
        
    - name: Send notification email if new release detected
      if: steps.latest-release.outputs.new_release == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: dify新版本发布：${{ steps.latest-release.outputs.tag_name }}
        html_body: |
          <h2>langgenius/dify 发布了新版本</h2>

          <p><strong> 版本:</strong> ${{ steps.latest-release.outputs.tag_name }} </p> 
          <p><strong>发布时间:</strong>  ${{ steps.latest-release.outputs.published_at }}</p>
          <p><strong>更新链接:</strong> <a href="${{ steps.latest-release.outputs.html_url }}">{{ steps.latest-release.outputs.html_url }}</a></p>
          <h5>更新内容:</h5> <p>${{ steps.latest-release.outputs.content }}</p>
        to: gaofan@deepexi.com
        from: ${{ secrets.EMAIL_USERNAME }}

    - name: Delete Previous Cache
      if: steps.latest-release.outputs.new_release == 'true'
      continue-on-error: true
      run: |
        gh cache delete last-release-version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update last release version
      if: steps.latest-release.outputs.new_release == 'true'
      shell: bash
      run: |
        echo "${{ steps.latest-release.outputs.tag_name }}" > last_release_version.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add last_release_version.txt
        git commit -m "Update last release version to ${{ steps.latest-release.outputs.tag_name }}"
        git push
