name: Dify Release Notifier

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:
    inputs:
      isrun:
        description: '是否运行'
        type: boolean
        required: false

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check latest release from langgenius/dify
      id: latest-release
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const markdown = require('markdown-it')();
          const release = await github.rest.repos.getLatestRelease({
            owner: 'langgenius',
            repo: 'dify'
          });
          const releaseDate = new Date(release.data.published_at);
          const chinaReleaseDate = releaseDate.toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' });
          const htmlBody = markdown.render(release.data.body);
          core.setOutput("tag_name", release.data.tag_name);
          core.setOutput("html_url", release.data.html_url);
          core.setOutput("content", htmlBody);
          core.setOutput("published_at", chinaReleaseDate);
        
    - name: Send notification email if new release detected
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: dify新版本发布：${{ steps.latest-release.outputs.tag_name }}
        body: |
          <h2>langgenius/dify 发布了新版本</h2>

          <p><strong> 版本:</strong> ${{ steps.latest-release.outputs.tag_name }} </p> 
          <p><strong>发布时间:</strong>  ${{ steps.latest-release.outputs.published_at }}</p>
          <p><strong>更新链接:</strong> <a href="${{ steps.latest-release.outputs.html_url }}">{{ steps.latest-release.outputs.html_url }}</a></p>
          <h5>更新内容:</h5> <p>${{ steps.latest-release.outputs.content }}</p>
        to: gaofan@deepexi.com
        from: ${{ secrets.EMAIL_USERNAME }}
